### PR TITLE
Remove tattoo tooltip and popup for cluster jewel keystones

### LINKED ISSUE #9736: Unique Small cluster notables error when right clicked
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Unique small cluster keystones show the "Tip" text to add a tattoo, but cannot be tattood over. The tooltip should not be shown and no action should be expected on right clicking the cluster keystone. Normal main tree keystones should probably be maintained for standard league.

### How does Path of Building behave?

Right clicking as per the tooltip producing the following error the following error:

Error:

In 'OnFrame': Classes/TreeTab.lua:840: attempt to index a nil value
stack traceback:
	Classes/TreeTab.lua:840: in function 'ModifyNodePopup'
	Classes/PassiveTreeView.lua:423: in function 'Draw'
	Classes/TreeTab.lua:442: in function 'Draw'
	Modules/Build.lua:1198: in function 'CallMode'
	Modules/Main.lua:370: in function <Modules/Main.lua:340>
	[C]: in function 'PCall'
	Launch.lua:111: in function <Launch.lua:108>
v2.63.0-454eff8c beta
Press Enter/Escape to dismiss, or F5 to restart the application.
Press CTRL + C to copy error text.

### How to reproduce the issue

Add any unique small cluster to a cluster jewel slot. Right click on the keystone.
Produced on beta version 2.63.0-454eff8c

### PoB for PoE1 build code

```shell
https://pobb.in/KGX_evRKBed2
```

### Screenshots

Setup: https://i.imgur.com/jJYYvR5.png
Error: https://i.imgur.com/791aEFu.png

### PR DESCRIPTION
**Pull request by Peechey**
Fixes #9736

### Description of the problem being solved:
Cluster jewel keystones are not allowed to be modified like usual tree keystones. This PR removes the "Tip" tooltip and returns early in the popup logic for keystone nodes with "expansionSkill".

### Steps taken to verify a working solution:
- Verify tooltip not found on cluster jewel keystone
- Verify right click does nothing on cluster jewel keystone
- Verify tree keystones unaffected

### Link to a build that showcases this PR:
<pre>https://pobb.in/KGX_evRKBed2</pre>

### Before screenshot:
image

### After screenshot:
image

### CODE REVIEW

File: src/Classes/TreeTab.lua [hunk 1]
```diff
@@ -838,6 +838,11 @@ function TreeTabClass:OpenExportPopup()
 end
 
 function TreeTabClass:ModifyNodePopup(selectedNode)
+	-- ignore cluster jewel Keystones like Secrets of Suffering
+	if selectedNode.type == "Keystone" and selectedNode.expansionSkill then
```
Comment (Wires77) [inline src/Classes/TreeTab.lua]: Any reason you didn't put this check with the others on line 503 of PassiveTreeView?

**Review by Wires77 — APPROVED** [review]
