### PR TITLE
Fix crash when hovering over more damage calc breakdown for Kinetic Fusillade of Destruction

### LINKED ISSUE #9735: Kinetic Fusillade of Detonation crash when hovering "MH Total More" with all projectiles option
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

Image

Image

### What are your system specifications and configuration?

Windows 11

### How to reproduce the issue

Go to calcs switch skill part to all projectiles and hover on "MH Total More"

### PoB for PoE1 build code

```shell

```

### PR DESCRIPTION
**Pull request by FenikSRT4**
Fixes #9735 

### Description of the problem being solved:
Regenerates the skills because of a reference to KineticFusilladeOfDestruction instead of to KineticFusilladeAltX which is the proper key for the skill. This reference was causing errors for some of the hover tooltips in the calcs tab.

I'm unsure if I should have allowed all of the generated changes, or just the one I'm targeting, but I figure because they are generated this would be expected. I am using the latest build of PoE as of the time of creating this PR.

### Steps taken to verify a working solution:
- Create a new build with any wand and Kinetic Fusillade of Destruction 
- Go to Calcs tab
- Verify all tooltips are working

### Before screenshot:
See issue.

### After screenshot:
image

### CODE REVIEW

File: src/Data/Skills/act_int.lua [hunk 1]
```diff
@@ -11479,7 +11479,7 @@ skills["KineticFusilladeAltX"] = {
 				-- Average multiplier: sum of (0, X, 2X, 3X, ..., (n-1)X) / n
 				-- This equals: X * (0 + 1 + 2 + ... + (n-1)) / n = X * n(n-1)/2 / n = X * (n-1)/2
 				local avgMoreMult = moreDamagePerProj * (output.ProjectileCount - 1) / 2
-				activeSkill.skillModList:NewMod("Damage", "MORE", avgMoreMult, "Skill:KineticFusilladeofDetonation", ModFlag.Hit)
+				activeSkill.skillModList:NewMod("Damage", "MORE", avgMoreMult, "Skill:KineticFusilladeAltX", ModFlag.Hit)
```
Comment (FenikSRT4) [inline src/Data/Skills/act_int.lua:11482]: This is the change that actually fixes the issue.

**Review by LocalIdentity — APPROVED** [review]
When you exported the gem from the game files, you were not using the latest update, which is why it removed lines. Please make sure in the future that you only commit lines that are relevant to your PR
I found the same crash on Charged Dash of Projection so fixed that too

**Comment by FenikSRT4** [comment]
> When you exported the gem from the game files, you were not using the latest update, which is why it removed lines. Please make sure in the future that you only commit lines that are relevant to your PR I found the same crash on Charged Dash of Projection so fixed that too

My apologies. I didn't realize that I had to set up another "source" for generating the file after updating the game through Steam. I tested that out this morning to conform my mistake.
