### PR TITLE
Fix two minion skill related crashes

### LINKED ISSUE #8914: Crash error on loading a character with Summon Raging Spirit of Enormity
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

When Summon Raging Spirit of Enormity is added to the build, PoB loses the ability to sort items by any method other than alphabetical. If the character is saved, then loading back into it causes a crash.

Image

### What are your system specifications and configuration?

Windows 10 Pro
Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz   2.11 GHz
8.00 GB (7.78 GB usable)

### How to reproduce the issue

Add Summon Raging Spirit of Enormity, try and sort items by something other than alphabetically, it looks like it randomizes them. Save the character and attempt to reload it, and it provides the crash message.

### PoB for PoE1 build code

```shell
https://pobb.in/W9AtLsJatAFA
```

### PR DESCRIPTION
**Pull request by Lothrik**
Fixes #8914.

### Description of the problem being solved:
Psuedo-skills (such as ``Enemies you Kill have a 15% chance to Explode, dealing a tenth of their maximum Life as Physical Damage`` from items, ``Profane Bloom`` from Occultist, ...) are somehow breaking minions, causing their skill lists to not load correctly. Luckily this is a temporary problem (not an unrecoverable state) meaning we can just ignore the errors when they happen, and set ``buildFlag = true`` to repair the damage after the fact.

### Steps taken to verify a working solution:
- Load linked build below in current PoB. Save the build and reload it.
- As long as you don't change anything in the build, you should get the ``Build.lua`` error immediately on load, and the ``SkillsTab.lua`` error if you apply the first half of the ``Build.lua`` patch (skip the ``self.buildFlag = true`` part), repeat the "save and reload" process, and then hover over the bugged minion in the skills tab itself.
- Once the full patch is applied, the linked build should never display either of the crashes from the screenshots below, no matter how many times you reload it. Note that you will see the Holy Relic's Nova skill pop into existence in the sidebar. That's ``buildMode:OnFrame(inputEvents)`` working as expected and repairing the bugged state the Holy Relic minion is in thanks to ``buildFlag = true`` being set.

### Link to a build that showcases this PR:
https://pobb.in/8QOBrbK0kabO

### Before screenshot:
image
image

### After screenshot:
N/A

### CODE REVIEW

File: src/Classes/SkillsTab.lua [hunk 1]
```diff
@@ -1212,6 +1212,9 @@ function SkillsTabClass:AddSocketGroupTooltip(tooltip, socketGroup)
 			if activeEffect.srcInstance then
 				gemShown[activeEffect.srcInstance] = true
 			end
+		elseif activeSkill.minion then
+			-- if `activeSkill.minion ~= nil` and `activeSkill.minion.mainSkill == nil`, we need to set `buildFlag = true` to fix this minion
```
Comment (Goruku) [inline src/Classes/SkillsTab.lua]: The comment itself doesn't say much about **why** this flag is necessary in both cases (**what** is getting fixed). You could reference an issue on the Github (for which the reference will stay active), or a concise description. This is mostly for the next dev going through the code.

**Review by Goruku — COMMENTED** [review]
I would like to see a "technical debt" style issue be created if this change goes through

**Review by LocalIdentity — APPROVED** [review]
